### ISSUE TITLE
ForestInsect-calgl does not compile

### ISSUE THREAD

**Issue by knotman90** [OpenCALTeam/opencal#1]
The example in GL version of OpenCal does not compile on UNIX system under gcc-5.1 and  freeglut opengl implementation.

```
In file included from ./opencal/OpenCAL-GL/examples/ForestInsect-calgl/source/forestInsect.c:1:0:
./opencal/OpenCAL-GL/examples/ForestInsect-calgl/source/forestInsect.h:46:12: error: field ‘windType’ has incomplete type

  enum WIND windType;
```
